from Prac_8.taxi import Taxi
new_taxi = Taxi("Prius 1", 100)
new_taxi.drive(40)
print(new_taxi.__str__())
print(new_taxi.start_fare())
new_taxi.drive(100)
print(new_taxi.__str__())
print(new_taxi.get_fare())
new_taxi.drive(20)
print(new_taxi.__str__())
print(new_taxi.get_fare())
new_taxi.drive(30)
print(new_taxi.__str__(), new_taxi.get_fare())